<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="manifest" href="/trainingapp/public/manifest.json"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="/trainingapp/public/css/app.css"><title>FitTrack — Kalendarz</title></head>
<body class="bg-slate-50 text-slate-900"><main class="mx-auto max-w-3xl px-4 pb-28 pt-6 space-y-6">
<header><a class="text-sm font-bold text-slate-500" href="/trainingapp/">← FitTrack</a><h1 class="mt-2 text-3xl font-black">Kalendarz</h1><p class="mt-1 text-slate-500">Planuj treningi i dni odpoczynku.</p></header>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-4"><h2 class="text-xl font-bold">Zaplanuj dzień</h2><form id="planForm" class="space-y-3"><label class="block text-sm font-semibold">Data<input class="mt-1 w-full rounded-xl border p-3" type="date" name="scheduled_date" required></label><label class="block text-sm font-semibold">Typ dnia<select class="mt-1 w-full rounded-xl border p-3" name="status"><option value="planned">Trening zaplanowany</option><option value="rest">Odpoczynek</option><option value="skipped">Pominięty</option></select></label><label class="block text-sm font-semibold">Plan treningowy<select class="mt-1 w-full rounded-xl border p-3" id="templateSelect" name="workout_template_id"><option value="">— bez planu / odpoczynek —</option></select></label><label class="block text-sm font-semibold">Notatka<textarea class="mt-1 w-full rounded-xl border p-3" name="notes" rows="2" placeholder="Opcjonalnie"></textarea></label><button class="w-full rounded-xl bg-slate-900 p-3 font-bold text-white">Zapisz w kalendarzu</button></form><p id="notice" class="text-sm"></p></section>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-4"><div class="flex items-center justify-between gap-3"><h2 class="text-xl font-bold">Plan miesiąca</h2><input id="month" type="month" class="rounded-xl border p-2"></div><div id="entries" class="space-y-3"><p class="text-slate-500">Ładowanie…</p></div></section>
</main><nav class="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 backdrop-blur"><div class="mx-auto grid max-w-3xl grid-cols-5 text-center text-xs font-bold"><a class="p-3" href="/trainingapp/">⌂<br>Home</a><a class="p-3 text-slate-900" href="/trainingapp/calendar.php">▦<br>Kalendarz</a><a class="p-3 text-slate-500" href="/trainingapp/workouts.php">◈<br>Treningi</a><a class="p-3 text-slate-500" href="/trainingapp/progress.php">↗<br>Progres</a><a class="p-3 text-slate-500" href="/trainingapp/nutrition.php">◉<br>Dieta</a></div></nav>
<script>
const API='/trainingapp/api';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(path,opts={}){const r=await fetch(API+'/'+path,{headers:{'Content-Type':'application/json'},...opts});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd API');return d}
const today=new Date();const pad=n=>String(n).padStart(2,'0');document.querySelector('[name=scheduled_date]').value=today.getFullYear()+'-'+pad(today.getMonth()+1)+'-'+pad(today.getDate());document.querySelector('#month').value=today.getFullYear()+'-'+pad(today.getMonth()+1);
let templates=[];
async function loadTemplates(){templates=await api('workout-templates');document.querySelector('#templateSelect').innerHTML='<option value="">— bez planu / odpoczynek —</option>'+templates.map(t=>'<option value="'+t.id+'">'+esc(t.name)+'</option>').join('')}
async function loadEntries(){const month=document.querySelector('#month').value;if(!month)return;const [y,m]=month.split('-').map(Number);const from=month+'-01';const to=month+'-'+pad(new Date(y,m,0).getDate());const rows=await api('calendar?from='+from+'&to='+to);const root=document.querySelector('#entries');if(!rows.length){root.innerHTML='<p class="rounded-xl bg-slate-50 p-4 text-slate-500">Brak wpisów w tym miesiącu.</p>';return}const labels={planned:'Zaplanowany',completed:'Ukończony',skipped:'Pominięty',rest:'Odpoczynek'};root.innerHTML=rows.map(x=>'<article class="flex items-center gap-3 rounded-2xl border p-4"><div class="min-w-0 flex-1"><p class="font-bold">'+esc(x.scheduled_date)+'</p><p class="text-sm text-slate-600">'+esc(x.workout_name||labels[x.status]||x.status)+'</p><p class="text-xs text-slate-400">'+esc(labels[x.status]||x.status)+(x.notes?' · '+esc(x.notes):'')+'</p></div>'+(x.status==='planned'&&x.workout_template_id?'<a class="rounded-xl bg-slate-900 px-3 py-2 text-sm font-bold text-white" href="/trainingapp/workout.php?scheduled_id='+x.id+'">Start</a>':'')+'<button class="delete rounded-xl border px-3 py-2 text-sm" data-id="'+x.id+'">Usuń</button></article>').join('');root.querySelectorAll('.delete').forEach(b=>b.onclick=async()=>{if(!confirm('Usunąć wpis z kalendarza?'))return;try{await api('calendar/'+b.dataset.id,{method:'DELETE'});await loadEntries()}catch(e){alert(e.message)}})}
document.querySelector('#month').onchange=()=>loadEntries().catch(showError);function showError(e){document.querySelector('#notice').textContent=e.message;document.querySelector('#notice').className='text-sm text-red-600'}
document.querySelector('#planForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const body={scheduled_date:f.get('scheduled_date'),status:f.get('status'),workout_template_id:f.get('workout_template_id')||null,notes:f.get('notes')};try{await api('calendar',{method:'POST',body:JSON.stringify(body)});document.querySelector('#notice').textContent='Zapisano wpis.';document.querySelector('#notice').className='text-sm text-emerald-700';document.querySelector('#month').value=body.scheduled_date.slice(0,7);await loadEntries()}catch(err){showError(err)}};
(async()=>{try{await loadTemplates();await loadEntries()}catch(e){showError(e);document.querySelector('#entries').innerHTML='<p class="text-red-600">Nie udało się pobrać kalendarza. Sprawdź połączenie z bazą danych.</p>'}})();
</script></body></html>