<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="manifest" href="/trainingapp/public/manifest.json"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="/trainingapp/public/css/app.css"><title>FitTrack — Baza ćwiczeń</title></head>
<body class="bg-slate-50 text-slate-900"><main class="mx-auto max-w-3xl px-4 pb-28 pt-6 space-y-6">
<header><a class="text-sm font-bold text-slate-500" href="/trainingapp/workouts.php">← Plany treningowe</a><h1 class="mt-2 text-3xl font-black">Baza ćwiczeń</h1><p class="mt-1 text-slate-500">Jedno miejsce do dodawania, poprawiania i archiwizowania ćwiczeń. Zmiany w bazie nie zmieniają zapisanych wyników treningów.</p></header>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-4"><div class="flex items-center justify-between gap-3"><h2 id="exerciseSectionTitle" class="text-xl font-bold">Baza ćwiczeń</h2><button id="newExercise" type="button" class="rounded-xl bg-slate-900 px-3 py-2 text-sm font-bold text-white">+ Dodaj ćwiczenie</button></div><p class="text-sm text-slate-500">Możesz dodawać własne ćwiczenia i edytować istniejące. Zarchiwizowane ćwiczenia nie będą dostępne w nowych planach.</p><input id="exerciseSearch" class="w-full rounded-xl border p-3" placeholder="Szukaj ćwiczeń"><div id="exerciseList" class="space-y-2">Ładowanie…</div>
<form id="exerciseForm" class="hidden space-y-3 rounded-2xl border bg-slate-50 p-4"><h3 id="exerciseFormTitle" class="font-bold">Nowe ćwiczenie</h3><input type="hidden" name="id"><label class="block text-sm font-semibold">Nazwa<input name="name" required maxlength="150" class="mt-1 w-full rounded-xl border p-3"></label><div class="grid grid-cols-2 gap-3"><label class="block text-sm font-semibold">Partia mięśniowa<select name="muscle_group" class="mt-1 w-full rounded-xl border p-3"><option>Klatka piersiowa</option><option>Plecy</option><option>Barki</option><option>Biceps</option><option>Triceps</option><option>Nogi</option><option>Pośladki</option><option>Brzuch</option><option>Łydki</option><option>Cardio</option><option>Całe ciało</option><option>Inne</option></select></label><label class="block text-sm font-semibold">Typ<select name="exercise_type" class="mt-1 w-full rounded-xl border p-3"><option value="strength">Siłowe</option><option value="bodyweight">Masa ciała</option><option value="time">Na czas</option></select></label></div><div class="grid grid-cols-2 gap-3"><label class="block text-sm font-semibold">Domyślna przerwa (sek.)<input name="default_rest_seconds" type="number" min="0" max="3600" step="1" value="90" required class="mt-1 w-full rounded-xl border p-3"><span class="mt-1 block text-xs font-normal text-slate-500">Przerwa po serii.</span></label><label class="block text-sm font-semibold">Domyślny czas serii (sek.)<input name="default_duration_seconds" type="number" min="1" max="3600" step="1" value="45" required class="mt-1 w-full rounded-xl border p-3"><span class="mt-1 block text-xs font-normal text-slate-500">Dla ćwiczeń „Na czas”, np. plank.</span></label></div><label class="block text-sm font-semibold">Notatki<textarea name="notes" rows="2" class="mt-1 w-full rounded-xl border p-3"></textarea></label><div class="grid grid-cols-2 gap-2"><button class="rounded-xl bg-emerald-700 p-3 font-bold text-white">Zapisz ćwiczenie</button><button id="cancelExercise" type="button" class="rounded-xl border p-3 font-bold">Anuluj</button></div><p id="exerciseNotice" class="text-sm"></p></form></section>
</main>
<nav class="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 backdrop-blur"><div class="mx-auto grid max-w-3xl grid-cols-5 text-center text-xs font-bold"><a class="p-3" href="/trainingapp/">⌂<br>Home</a><a class="p-3 text-slate-500" href="/trainingapp/calendar.php">▦<br>Kalendarz</a><a class="p-3" href="/trainingapp/workouts.php">◈<br>Treningi</a><a class="p-3 text-slate-500" href="/trainingapp/progress.php">↗<br>Progres</a><a class="p-3 text-slate-500" href="/trainingapp/nutrition.php">◉<br>Dieta</a></div></nav>
<script>
const API='/trainingapp/api';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(p,o={}){const r=await fetch(API+'/'+p,{headers:{'Content-Type':'application/json'},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd API');return d}
let exercises=[];
function renderExerciseList(){const q=document.querySelector('#exerciseSearch').value.toLowerCase();const list=exercises.filter(x=>(x.name+' '+(x.muscle_group||'')).toLowerCase().includes(q));document.querySelector('#exerciseList').innerHTML=list.map(x=>'<article class="flex items-center gap-3 rounded-xl border p-3"><div class="min-w-0 flex-1"><p class="font-semibold">'+esc(x.name)+'</p><p class="text-xs text-slate-500">'+esc(x.muscle_group||'Inne')+' · '+({'strength':'siłowe','bodyweight':'masa ciała','time':'na czas'}[x.exercise_type]||'siłowe')+(x.exercise_type==='time'?' · seria '+Number(x.default_duration_seconds??45)+' s':'')+' · przerwa domyślna '+Number(x.default_rest_seconds??90)+' s</p></div><button type="button" class="edit-exercise rounded-lg border px-3 py-2 text-sm font-bold" data-id="'+x.id+'">Edytuj</button><button type="button" class="archive-exercise rounded-lg border px-3 py-2 text-sm" data-id="'+x.id+'">Archiwizuj</button></article>').join('')||'<p class="text-sm text-slate-500">Brak ćwiczeń.</p>';document.querySelectorAll('.edit-exercise').forEach(b=>b.onclick=()=>editExercise(Number(b.dataset.id)));document.querySelectorAll('.archive-exercise').forEach(b=>b.onclick=async()=>{if(!confirm('Zarchiwizować ćwiczenie? Nie będzie dostępne w nowych planach.'))return;try{await api('exercises/'+b.dataset.id,{method:'DELETE'});await load()}catch(e){alert(e.message)}})}
function resetExerciseForm(){const f=document.querySelector('#exerciseForm');f.reset();f.elements.id.value='';f.classList.add('hidden');document.querySelector('#exerciseNotice').textContent=''}
function editExercise(id){const x=exercises.find(e=>Number(e.id)===id);if(!x)return;const f=document.querySelector('#exerciseForm');f.classList.remove('hidden');f.elements.id.value=x.id;f.elements.name.value=x.name;f.elements.muscle_group.value=x.muscle_group||'Inne';f.elements.exercise_type.value=x.exercise_type||'strength';f.elements.default_rest_seconds.value=x.default_rest_seconds??90;f.elements.default_duration_seconds.value=x.default_duration_seconds??45;f.elements.notes.value=x.notes||'';document.querySelector('#exerciseFormTitle').textContent='Edytuj ćwiczenie';f.scrollIntoView({behavior:'smooth',block:'center'})}
document.querySelector('#newExercise').onclick=()=>{resetExerciseForm();document.querySelector('#exerciseForm').classList.remove('hidden');document.querySelector('#exerciseFormTitle').textContent='Dodaj ćwiczenie';document.querySelector('#exerciseForm').scrollIntoView({behavior:'smooth',block:'center'})};
document.querySelector('#cancelExercise').onclick=resetExerciseForm;
document.querySelector('#exerciseSearch').oninput=renderExerciseList;
document.querySelector('#exerciseForm').onsubmit=async e=>{e.preventDefault();const f=e.target,d={name:f.elements.name.value.trim(),muscle_group:f.elements.muscle_group.value,exercise_type:f.elements.exercise_type.value,default_rest_seconds:Number(f.elements.default_rest_seconds.value??90),default_duration_seconds:Number(f.elements.default_duration_seconds.value??45),notes:f.elements.notes.value};try{const id=f.elements.id.value;await api(id?'exercises/'+id:'exercises',{method:id?'PUT':'POST',body:JSON.stringify(d)});await load();resetExerciseForm()}catch(err){document.querySelector('#exerciseNotice').textContent=err.message;document.querySelector('#exerciseNotice').className='text-sm text-red-600'}};
async function load(){exercises=await api('exercises');renderExerciseList()}
load().catch(e=>{document.querySelector('#exerciseList').textContent='Nie udało się pobrać ćwiczeń: '+e.message});
</script></body></html>