<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="manifest" href="/trainingapp/public/manifest.json"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="/trainingapp/public/css/app.css"><title>FitTrack — Dieta</title></head>
<body class="bg-slate-50 text-slate-900"><main class="mx-auto max-w-3xl px-4 pb-28 pt-6 space-y-6"><header><a class="text-sm font-bold text-slate-500" href="/trainingapp/">← FitTrack</a><h1 class="mt-2 text-3xl font-black">Dieta i makro</h1><p class="mt-1 text-slate-500">Zapisuj dzienne kalorie, makroskładniki i kroki.</p></header>
<section class="grid grid-cols-2 gap-3"><div class="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p class="text-sm text-slate-500">Cel kalorii</p><p id="goalCal" class="mt-1 text-2xl font-black">—</p></div><div class="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p class="text-sm text-slate-500">Cel białka</p><p id="goalProtein" class="mt-1 text-2xl font-black">—</p></div></section>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-4"><h2 class="text-xl font-bold">Dzienny wpis</h2><form id="form" class="grid grid-cols-2 gap-3"><label class="col-span-2 text-sm font-semibold">Data<input name="entry_date" type="date" required class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Kalorie<input name="calories" type="number" min="0" required value="0" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Białko (g)<input name="protein_g" type="number" min="0" step="0.1" value="0" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Węglowodany (g)<input name="carbs_g" type="number" min="0" step="0.1" value="0" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Tłuszcze (g)<input name="fats_g" type="number" min="0" step="0.1" value="0" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Kroki<input name="steps" type="number" min="0" value="0" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Spalone kcal<input name="burned_calories" type="number" min="0" value="0" class="mt-1 w-full rounded-xl border p-3"></label><label class="col-span-2 text-sm font-semibold">Notatka<textarea name="notes" rows="2" class="mt-1 w-full rounded-xl border p-3"></textarea></label><button class="col-span-2 rounded-xl bg-slate-900 p-3 font-bold text-white">Zapisz dzień</button><p id="notice" class="col-span-2 text-sm"></p></form></section>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-3"><div class="flex items-center justify-between gap-3"><h2 class="text-xl font-bold">Historia</h2><input id="month" type="month" class="rounded-xl border p-2"></div><div id="history" class="space-y-3">Ładowanie…</div></section></main>
<nav class="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 backdrop-blur"><div class="mx-auto grid max-w-3xl grid-cols-5 text-center text-xs font-bold"><a class="p-3" href="/trainingapp/">⌂<br>Home</a><a class="p-3 text-slate-500" href="/trainingapp/calendar.php">▦<br>Kalendarz</a><a class="p-3 text-slate-500" href="/trainingapp/workouts.php">◈<br>Treningi</a><a class="p-3 text-slate-500" href="/trainingapp/progress.php">↗<br>Progres</a><a class="p-3" href="/trainingapp/nutrition.php">◉<br>Dieta</a></div></nav>
<script>
const API='/trainingapp/api';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(p,o={}){const r=await fetch(API+'/'+p,{headers:{'Content-Type':'application/json'},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd API');return d}const now=new Date(),pad=n=>String(n).padStart(2,'0'),date=now.getFullYear()+'-'+pad(now.getMonth()+1)+'-'+pad(now.getDate());document.querySelector('[name=entry_date]').value=date;document.querySelector('#month').value=date.slice(0,7);
let rows=[];async function load(){const settings=await api('settings');document.querySelector('#goalCal').textContent=(settings.daily_calories||2500)+' kcal';document.querySelector('#goalProtein').textContent=(settings.daily_protein_g||190)+' g';const month=document.querySelector('#month').value;const [y,m]=month.split('-').map(Number);rows=await api('nutrition?from='+month+'-01&to='+month+'-'+pad(new Date(y,m,0).getDate()));render()}
function render(){const root=document.querySelector('#history');root.innerHTML=rows.slice().reverse().map(x=>'<article class="rounded-2xl border p-4"><div class="flex items-center justify-between gap-2"><h3 class="font-bold">'+esc(x.entry_date)+'</h3><button class="edit rounded-lg border px-3 py-1 text-sm" data-date="'+x.entry_date+'">Edytuj</button></div><p class="mt-2 text-lg font-black">'+x.calories+' kcal</p><p class="text-sm text-slate-500">Białko '+x.protein_g+' g · Węglowodany '+x.carbs_g+' g · Tłuszcze '+x.fats_g+' g</p><p class="text-sm text-slate-500">Kroki: '+(x.steps??'—')+(x.burned_calories?' · Spalone: '+x.burned_calories+' kcal':'')+'</p>'+(x.notes?'<p class="mt-2 text-sm">'+esc(x.notes)+'</p>':'')+'</article>').join('')||'<p class="text-slate-500">Brak wpisów w tym miesiącu.</p>';root.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{const x=rows.find(x=>x.entry_date===b.dataset.date);if(!x)return;for(const [k,v] of Object.entries(x)){const el=document.querySelector('[name="'+k+'"]');if(el)el.value=v??''}window.scrollTo({top:0,behavior:'smooth'})})}
document.querySelector('#month').onchange=()=>load().catch(showError);function showError(e){const n=document.querySelector('#notice');n.textContent=e.message;n.className='col-span-2 text-sm text-red-600'}
document.querySelector('#form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const body=Object.fromEntries(f.entries());for(const k of ['calories','protein_g','carbs_g','fats_g','steps','burned_calories'])body[k]=body[k]===''?null:Number(body[k]);try{await api('nutrition',{method:'POST',body:JSON.stringify(body)});document.querySelector('#notice').textContent='Wpis zapisany.';document.querySelector('#notice').className='col-span-2 text-sm text-emerald-700';document.querySelector('#month').value=body.entry_date.slice(0,7);await load()}catch(err){showError(err)}};
load().catch(showError);
</script></body></html>