<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="manifest" href="/trainingapp/public/manifest.json"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="/trainingapp/public/css/app.css"><title>FitTrack — Progres</title></head>
<body class="bg-slate-50 text-slate-900"><main class="mx-auto max-w-3xl px-4 pb-28 pt-6 space-y-6"><header><a class="text-sm font-bold text-slate-500" href="/trainingapp/">← FitTrack</a><h1 class="mt-2 text-3xl font-black">Progres</h1><p class="mt-1 text-slate-500">Mierz postępy i obserwuj zmiany sylwetki.</p></header>
<section class="grid grid-cols-2 gap-3"><div class="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p class="text-sm text-slate-500">Ostatnia masa</p><p id="latestWeight" class="mt-1 text-2xl font-black">—</p></div><div class="rounded-2xl bg-white p-4 ring-1 ring-slate-200"><p class="text-sm text-slate-500">Zmiana od pierwszego pomiaru</p><p id="weightChange" class="mt-1 text-2xl font-black">—</p></div></section>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-4"><h2 class="text-xl font-bold">Dodaj pomiar</h2><form id="form" class="grid grid-cols-2 gap-3"><label class="col-span-2 text-sm font-semibold">Data pomiaru<input name="measurement_date" type="date" required class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Masa (kg)<input name="weight_kg" type="number" min="0" step="0.1" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Talia (cm)<input name="waist_cm" type="number" min="0" step="0.1" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Klatka (cm)<input name="chest_cm" type="number" min="0" step="0.1" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Ramię (cm)<input name="arm_cm" type="number" min="0" step="0.1" class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Udo (cm)<input name="thigh_cm" type="number" min="0" step="0.1" class="mt-1 w-full rounded-xl border p-3"></label><button class="col-span-2 rounded-xl bg-slate-900 p-3 font-bold text-white">Zapisz pomiar</button><p id="notice" class="col-span-2 text-sm"></p></form></section>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-3"><h2 class="text-xl font-bold">Historia pomiarów</h2><div id="history" class="space-y-3">Ładowanie…</div></section>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-3"><h2 class="text-xl font-bold">Historia treningów</h2><div id="sessions" class="space-y-3">Ładowanie…</div></section></main>
<nav class="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 backdrop-blur"><div class="mx-auto grid max-w-3xl grid-cols-5 text-center text-xs font-bold"><a class="p-3" href="/trainingapp/">⌂<br>Home</a><a class="p-3 text-slate-500" href="/trainingapp/calendar.php">▦<br>Kalendarz</a><a class="p-3 text-slate-500" href="/trainingapp/workouts.php">◈<br>Treningi</a><a class="p-3" href="/trainingapp/progress.php">↗<br>Progres</a><a class="p-3 text-slate-500" href="/trainingapp/nutrition.php">◉<br>Dieta</a></div></nav>
<script>
const API='/trainingapp/api';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(p,o={}){const r=await fetch(API+'/'+p,{headers:{'Content-Type':'application/json'},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd API');return d}const now=new Date(),pad=n=>String(n).padStart(2,'0');document.querySelector('[name=measurement_date]').value=now.getFullYear()+'-'+pad(now.getMonth()+1)+'-'+pad(now.getDate());
async function load(){const [measurements,sessions]=await Promise.all([api('measurements'),api('workout-sessions?limit=30')]);const weights=measurements.filter(x=>x.weight_kg!==null&&x.weight_kg!=='').slice().sort((a,b)=>a.measurement_date.localeCompare(b.measurement_date));document.querySelector('#latestWeight').textContent=weights.length?Number(weights[weights.length-1].weight_kg).toFixed(1)+' kg':'—';if(weights.length>1){const delta=Number(weights[weights.length-1].weight_kg)-Number(weights[0].weight_kg);document.querySelector('#weightChange').textContent=(delta>0?'+':'')+delta.toFixed(1)+' kg';document.querySelector('#weightChange').className='mt-1 text-2xl font-black '+(delta<0?'text-emerald-700':'')}else document.querySelector('#weightChange').textContent='—';
document.querySelector('#history').innerHTML=measurements.map(x=>'<article class="rounded-2xl border p-4"><h3 class="font-bold">'+esc(x.measurement_date)+'</h3><p class="mt-1 text-lg font-black">'+(x.weight_kg!==null?x.weight_kg+' kg':'Brak masy')+'</p><p class="text-sm text-slate-500">Talia '+(x.waist_cm??'—')+' cm · Klatka '+(x.chest_cm??'—')+' cm · Ramię '+(x.arm_cm??'—')+' cm · Udo '+(x.thigh_cm??'—')+' cm</p><button class="edit mt-2 rounded-lg border px-3 py-2 text-sm" data-date="'+x.measurement_date+'">Edytuj pomiar</button></article>').join('')||'<p class="text-slate-500">Dodaj pierwszy pomiar, aby rozpocząć śledzenie progresu.</p>';document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>{const x=measurements.find(x=>x.measurement_date===b.dataset.date);for(const [k,v] of Object.entries(x)){const el=document.querySelector('[name="'+k+'"]');if(el)el.value=v??''}window.scrollTo({top:0,behavior:'smooth'})});
document.querySelector('#sessions').innerHTML=sessions.map(x=>'<article class="rounded-2xl border p-4"><h3 class="font-bold">'+esc(x.workout_name_snapshot)+'</h3><p class="text-sm text-slate-500">'+esc(x.started_at)+' · '+(x.ended_at?'Zakończony':'W trakcie')+'</p><p class="mt-1 text-sm">'+(x.exercise_count||0)+' ćwiczeń · '+(x.set_count||0)+' serii'+(x.duration_seconds?' · '+Math.round(x.duration_seconds/60)+' min':'')+'</p><a class="mt-2 inline-flex rounded-lg border px-3 py-2 text-sm" href="/trainingapp/workout.php?session_id='+x.id+'">'+(x.ended_at?'Podgląd':'Wróć do treningu')+'</a></article>').join('')||'<p class="text-slate-500">Historia treningów pojawi się tutaj po pierwszej sesji.</p>'}
function showError(e){const n=document.querySelector('#notice');n.textContent=e.message;n.className='col-span-2 text-sm text-red-600'}
document.querySelector('#form').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target).entries());for(const k of ['weight_kg','waist_cm','chest_cm','arm_cm','thigh_cm'])body[k]=body[k]===''?null:Number(body[k]);try{await api('measurements',{method:'POST',body:JSON.stringify(body)});document.querySelector('#notice').textContent='Pomiar zapisany.';document.querySelector('#notice').className='col-span-2 text-sm text-emerald-700';await load()}catch(err){showError(err)}};load().catch(showError);
</script></body></html>