<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="manifest" href="/trainingapp/public/manifest.json"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="/trainingapp/public/css/app.css"><title>FitTrack — Ustawienia</title></head>
<body class="bg-slate-50 text-slate-900"><main class="mx-auto max-w-3xl px-4 pb-28 pt-6 space-y-6"><header><a class="text-sm font-bold text-slate-500" href="/trainingapp/index.php">← FitTrack</a><h1 class="mt-2 text-3xl font-black">Ustawienia</h1><p class="mt-1 text-slate-500">Ustal dzienne cele diety i cel masy ciała.</p></header>
<section class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-4"><h2 class="text-xl font-bold">Cele żywieniowe</h2><form id="form" class="grid grid-cols-2 gap-3"><label class="col-span-2 text-sm font-semibold">Cel kalorii (kcal)<input name="daily_calories" type="number" min="1" max="15000" required class="mt-1 w-full rounded-xl border p-3"></label><label class="col-span-2 text-sm font-semibold">Szacowane zapotrzebowanie na utrzymanie wagi (kcal/dzień)<input name="maintenance_calories" type="number" min="1" max="15000" required class="mt-1 w-full rounded-xl border p-3"><span class="mt-1 block text-xs font-normal text-slate-500">Używane do szacowania dziennego i tygodniowego deficytu. Na start możesz ustawić 3100 kcal, a potem skorygować na podstawie trendu wagi.</span></label><label class="text-sm font-semibold">Białko (g)<input name="daily_protein_g" type="number" min="0" max="1000" required class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Węglowodany (g)<input name="daily_carbs_g" type="number" min="0" max="1500" required class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Tłuszcze (g)<input name="daily_fats_g" type="number" min="0" max="1000" required class="mt-1 w-full rounded-xl border p-3"></label><label class="text-sm font-semibold">Docelowa masa (kg)<input name="goal_weight_kg" type="number" min="1" max="500" step="0.1" class="mt-1 w-full rounded-xl border p-3"></label><button class="col-span-2 rounded-xl bg-slate-900 p-3 font-bold text-white">Zapisz ustawienia</button><p id="notice" class="col-span-2 text-sm"></p></form></section>
<section class="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><h2 class="font-bold">Jak liczymy postęp?</h2><p class="mt-2 text-sm text-slate-600">Tygodniowy bilans deficytu szacujemy jako zapotrzebowanie na utrzymanie wagi minus faktycznie spożyte kalorie. Dni bez wpisu oznaczamy jako brak danych. Kalorie z zegarka nie są dodawane drugi raz do deficytu.</p></section></main>
<nav class="fixed inset-x-0 bottom-0 z-40 border-t bg-white/95 backdrop-blur"><div class="mx-auto grid max-w-3xl grid-cols-5 text-center text-xs font-bold"><a class="p-3" href="/trainingapp/index.php">⌂<br>Home</a><a class="p-3 text-slate-500" href="/trainingapp/calendar.php">▦<br>Kalendarz</a><a class="p-3 text-slate-500" href="/trainingapp/workouts.php">◈<br>Treningi</a><a class="p-3 text-slate-500" href="/trainingapp/progress.php">↗<br>Progres</a><a class="p-3 text-slate-500" href="/trainingapp/nutrition.php">◉<br>Dieta</a></div></nav>
<script>
const API='/trainingapp/api';async function api(p,o={}){const r=await fetch(API+'/'+p,{headers:{'Content-Type':'application/json'},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd API');return d}
const form=document.querySelector('#form');async function load(){const s=await api('settings');for(const k of ['daily_calories','maintenance_calories','daily_protein_g','daily_carbs_g','daily_fats_g','goal_weight_kg'])form.elements[k].value=s[k]??({'daily_calories':2450,'maintenance_calories':3100,'daily_protein_g':190,'daily_carbs_g':265,'daily_fats_g':70}[k]??'')}
form.onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form).entries());try{await api('settings',{method:'POST',body:JSON.stringify(data)});const n=document.querySelector('#notice');n.textContent='Ustawienia zapisane.';n.className='col-span-2 text-sm text-emerald-700'}catch(err){const n=document.querySelector('#notice');n.textContent=err.message;n.className='col-span-2 text-sm text-red-600'}};load().catch(e=>{document.querySelector('#notice').textContent=e.message});
</script></body></html>