<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="manifest" href="/trainingapp/public/manifest.json"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="/trainingapp/public/css/app.css"><title>FitTrack — Trening</title>
<style>
:root{color-scheme:light}body{min-height:100dvh}input,button,textarea{font:inherit}input{font-size:18px}button{touch-action:manipulation}.safe-bottom{padding-bottom:calc(1rem + env(safe-area-inset-bottom))}.big-clock{font-variant-numeric:tabular-nums;letter-spacing:-.05em}
</style></head>
<body class="bg-slate-100 text-slate-900 antialiased">
<main class="mx-auto flex min-h-[100dvh] max-w-2xl flex-col px-4 pb-5 pt-4 sm:pt-6">
<header class="mb-4">
<div class="flex items-center justify-between gap-3"><a href="/trainingapp/workouts.php" class="text-sm font-bold text-slate-500">← Wyjdź z treningu</a><span id="stepCounter" class="rounded-full bg-slate-200 px-3 py-1 text-xs font-bold">Ładowanie</span></div>
<h1 id="title" class="mt-3 text-2xl font-black sm:text-3xl">Trening</h1>
<div class="mt-3 flex items-center justify-between rounded-2xl bg-slate-900 px-4 py-3 text-white"><div><p class="text-xs font-semibold text-slate-300">CZAS TRENINGU</p><p id="timer" class="text-2xl font-black tabular-nums">00:00:00</p></div><div class="text-right"><p class="text-xs text-slate-300">Wykonane serie</p><p id="setProgress" class="text-lg font-bold">0 / 0</p></div></div>
</header>
<div id="notice" class="mb-3 text-sm" role="status" aria-live="polite"></div>
<section id="exerciseArea" class="flex flex-1 flex-col"><div class="rounded-3xl bg-white p-5">Przygotowywanie treningu…</div></section>
<section id="finishArea" class="hidden safe-bottom mt-4 rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200">
<h2 class="text-xl font-black">Podsumowanie treningu</h2><p id="finishIntro" class="mt-1 text-sm text-slate-500"></p><div id="summary" class="mt-4 space-y-2"></div>
<label id="notesWrap" class="mt-4 block text-sm font-semibold">Notatka z treningu<textarea id="sessionNotes" rows="2" class="mt-1 w-full rounded-xl border p-3 font-normal"></textarea></label>
<button id="finish" class="mt-4 w-full rounded-2xl bg-emerald-600 p-4 text-lg font-black text-white shadow-sm">Zakończ trening</button>
<a href="/trainingapp/" class="mt-2 block rounded-2xl border p-3 text-center font-bold">Wróć do strony głównej</a>
</section>
</main>
<script>
const API='/trainingapp/api';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function api(p,o={}){const r=await fetch(API+'/'+p,{headers:{'Content-Type':'application/json'},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd API');return d}
const params=new URLSearchParams(location.search);let session=null,timerHandle=null,uiHandle=null,restHandle=null,timerFetchedAt=Date.now(),flow={};
const flowKey=()=> 'fittrack-workout-flow-'+session.id;
function loadFlow(){try{flow=JSON.parse(localStorage.getItem(flowKey())||'{}')}catch{flow={}}}
function saveFlow(){try{localStorage.setItem(flowKey(),JSON.stringify(flow))}catch{}}
function elapsed(){if(!session)return 0;return Math.max(0,Number(session.elapsed_seconds)||0)+(session.ended_at?0:Math.floor((Date.now()-timerFetchedAt)/1000))}
function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?String(h).padStart(2,'0')+':'+String(m).padStart(2,'0')+':'+String(s).padStart(2,'0'):String(m).padStart(2,'0')+':'+String(s).padStart(2,'0')}
function updateTimer(){document.querySelector('#timer').textContent=fmt(elapsed())}
function allSets(){return session?.sets||[]}
function setsFor(ex){return allSets().filter(s=>String(s.workout_session_exercise_id)===String(ex.id))}
function targetSets(ex){return Math.max(1,Number(ex.sets_target)||3)}
function totalSets(){return (session?.exercises||[]).reduce((a,e)=>a+targetSets(e),0)}
function doneSets(){return (session?.exercises||[]).reduce((a,e)=>a+setsFor(e).filter(s=>Number(s.set_number)<=targetSets(e)).length,0)}
function findNext(){for(let i=0;i<(session.exercises||[]).length;i++){const ex=session.exercises[i],saved=new Set(setsFor(ex).map(s=>Number(s.set_number)));for(let n=1;n<=targetSets(ex);n++)if(!saved.has(n))return {exerciseIndex:i,setNumber:n}}return null}
function currentFlow(){const next=findNext();if(!next)return null;if(flow.exerciseIndex!==next.exerciseIndex||flow.setNumber!==next.setNumber){flow.exerciseIndex=next.exerciseIndex;flow.setNumber=next.setNumber;flow.restUntil=null;saveFlow()}return next}
function startExerciseClock(ex){if(!flow.exerciseStartedAt)flow.exerciseStartedAt=Date.now();flow.exerciseStarts=flow.exerciseStarts||{};if(!flow.exerciseStarts[ex.id])flow.exerciseStarts[ex.id]=Date.now();saveFlow()}
function previousFor(ex,n){return (ex.previous_sets||[]).find(s=>Number(s.set_number)===n)}
function render(){document.querySelector('#title').textContent=session.workout_name_snapshot||'Trening';document.querySelector('#setProgress').textContent=doneSets()+' / '+totalSets();
const root=document.querySelector('#exerciseArea');const finish=document.querySelector('#finishArea');
if(session.ended_at){root.innerHTML='<div class="rounded-3xl bg-emerald-50 p-5 text-emerald-900"><p class="text-xl font-black">Trening zakończony!</p><p class="mt-1">Wyniki są zapisane w historii.</p></div>';finish.classList.remove('hidden');document.querySelector('#finish').classList.add('hidden');document.querySelector('#notesWrap').classList.add('hidden');document.querySelector('#finishIntro').textContent='Łączny czas: '+fmt(Number(session.duration_seconds)||elapsed());renderSummary();return}
const next=currentFlow();if(!next){renderFinishReady();return}
const ex=session.exercises[next.exerciseIndex],n=next.setNumber,timed=ex.exercise_type==='time',previous=previousFor(ex,n),saved=setsFor(ex).find(s=>Number(s.set_number)===n);
document.querySelector('#stepCounter').textContent='Ćwiczenie '+(next.exerciseIndex+1)+' z '+session.exercises.length;
startExerciseClock(ex);finish.classList.add('hidden');
const target=timed?(ex.min_reps_target?ex.min_reps_target+' s':'według planu'):(ex.min_reps_target?ex.min_reps_target+(ex.max_reps_target&&ex.max_reps_target!==ex.min_reps_target?'-'+ex.max_reps_target:'')+' powt.':'według planu');
const prevText=previous?(timed?'Ostatnio: '+previous.reps+' s':'Ostatnio: '+(previous.weight_kg??0)+' kg × '+previous.reps+' powt.'):'Brak wyniku z poprzedniego treningu';
if(flow.restUntil&&flow.restUntil>Date.now()){renderRest(ex,next);return}
flow.restUntil=null;saveFlow();
root.innerHTML='<div class="flex flex-1 flex-col gap-4"><div class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-wider text-slate-500">Ćwiczenie '+(next.exerciseIndex+1)+' / '+session.exercises.length+'</p><h2 class="mt-1 text-2xl font-black leading-tight sm:text-3xl">'+esc(ex.exercise_name_snapshot)+'</h2><p class="mt-2 text-sm text-slate-500">'+esc(ex.muscle_group||'')+' · cel: '+target+'</p></div><div class="shrink-0 rounded-2xl bg-slate-100 px-3 py-2 text-center"><p class="text-[10px] font-bold uppercase text-slate-500">Seria</p><p class="text-2xl font-black">'+n+'<span class="text-sm text-slate-400">/'+targetSets(ex)+'</span></p></div></div><div class="mt-4 rounded-xl bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-900">'+esc(prevText)+'</div></div>
<div class="flex flex-1 flex-col rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div class="mb-4"><h3 class="text-lg font-black">Wynik tej serii</h3><p class="text-sm text-slate-500">Wpisz wynik i przejdź dalej.</p></div><form id="setForm" class="flex flex-1 flex-col gap-4"><div class="grid '+(timed?'grid-cols-1':'grid-cols-2')+' gap-3">'+(timed?'':'<label class="block text-sm font-bold">Ciężar (kg)<input id="weight" type="number" min="0" step="0.5" inputmode="decimal" value="'+(saved?.weight_kg??previous?.weight_kg??'')+'" placeholder="np. 40" class="mt-2 w-full rounded-2xl border-2 border-slate-200 bg-white p-4 text-2xl font-black focus:border-slate-900 focus:outline-none" required></label>')+'<label class="block text-sm font-bold">'+(timed?'Czas (sek.)':'Powtórzenia')+'<input id="reps" type="number" min="1" step="1" inputmode="numeric" value="'+(saved?.reps??(timed?ex.min_reps_target??'':previous?.reps??''))+'" placeholder="'+(timed?'np. 45':'np. 10')+'" class="mt-2 w-full rounded-2xl border-2 border-slate-200 bg-white p-4 text-2xl font-black focus:border-slate-900 focus:outline-none" required></label></div><label class="block text-sm font-bold">RIR <span class="font-normal text-slate-400">(opcjonalnie)</span><input id="rir" type="number" min="0" max="10" step="0.5" inputmode="decimal" value="'+(saved?.rir??'')+'" placeholder="np. 2" class="mt-2 w-full rounded-2xl border-2 border-slate-200 bg-white p-4 text-xl font-bold focus:border-slate-900 focus:outline-none"></label><div class="mt-auto rounded-xl bg-slate-50 p-3 text-sm text-slate-500">Przerwa po serii: <strong class="text-slate-800">'+(n<targetSets(ex)?(Number(ex.rest_seconds)||90)+' s':(next.exerciseIndex<session.exercises.length-1?'3 min przed kolejnym ćwiczeniem':'koniec treningu po tej serii'))+'</strong></div><button class="mt-2 w-full rounded-2xl bg-slate-900 p-4 text-lg font-black text-white shadow-sm" type="submit">'+(n===targetSets(ex)&&next.exerciseIndex===session.exercises.length-1?'Zapisz serię i zakończ':'Zapisz serię i dalej →')+'</button></form></div></div>';
document.querySelector('#setForm').onsubmit=async e=>{e.preventDefault();const reps=document.querySelector('#reps').value;if(!reps||Number(reps)<1){notice(timed?'Podaj czas większy od zera.':'Podaj liczbę powtórzeń większą od zera.',true);return}const btn=e.target.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Zapisywanie…';try{await api('workout-sessions/'+session.id+'/sets',{method:'POST',body:JSON.stringify({workout_session_exercise_id:Number(ex.id),set_number:n,weight_kg:timed?0:Number(document.querySelector('#weight')?.value||0),reps:Number(reps),rir:document.querySelector('#rir').value===''?null:Number(document.querySelector('#rir').value)})});session=await api('workout-sessions/'+session.id);timerFetchedAt=Date.now();flow.completedSetAt=Date.now();const lastSet=n>=targetSets(ex),lastExercise=next.exerciseIndex>=session.exercises.length-1;if(lastSet){flow.exerciseDurations=flow.exerciseDurations||{};const started=Number(flow.exerciseStarts?.[ex.id]||flow.exerciseStartedAt||Date.now());flow.exerciseDurations[ex.id]=Math.max(1,Math.floor((Date.now()-started)/1000));flow.exerciseIndex=next.exerciseIndex+1;flow.setNumber=1}else{flow.exerciseIndex=next.exerciseIndex;flow.setNumber=n+1}if(lastSet&&lastExercise){flow.restUntil=null;saveFlow();renderFinishReady();return}const restSeconds=lastSet?180:(Number(ex.rest_seconds)||90);flow.restUntil=Date.now()+restSeconds*1000;flow.restKind=lastSet?'exercise':'set';flow.restExerciseId=ex.id;flow.restExerciseName=ex.exercise_name_snapshot;flow.restNextExerciseIndex=flow.exerciseIndex;flow.restNextSetNumber=flow.setNumber;saveFlow();renderRest(ex,{exerciseIndex:next.exerciseIndex,setNumber:n});}catch(err){notice(err.message,true);btn.disabled=false;btn.textContent='Spróbuj ponownie'}}}
function renderRest(ex,oldNext){const root=document.querySelector('#exerciseArea');const until=Number(flow.restUntil)||Date.now();const isExercise=flow.restKind==='exercise';const next= findNext();const nextEx=next?session.exercises[next.exerciseIndex]:null;root.innerHTML='<div class="flex flex-1 flex-col items-center justify-center rounded-3xl bg-slate-900 px-5 py-8 text-center text-white shadow-xl"><div class="rounded-full bg-white/10 px-4 py-2 text-xs font-black uppercase tracking-widest">'+(isExercise?'Przerwa między ćwiczeniami':'Przerwa między seriami')+'</div><p class="mt-6 text-sm text-slate-300">Zrobiono: '+esc(ex.exercise_name_snapshot)+'</p><div id="restClock" class="big-clock mt-2 text-7xl font-black sm:text-8xl">'+fmt(Math.ceil((until-Date.now())/1000))+'</div><p class="mt-3 text-slate-300">'+(isExercise?(nextEx?'Następne: '+esc(nextEx.exercise_name_snapshot):'Świetna robota!'):'Odpocznij. Kolejna seria za chwilę.')+'</p><div class="mt-8 w-full max-w-sm space-y-3"><button id="skipRest" class="w-full rounded-2xl bg-white p-4 text-lg font-black text-slate-900">Pomiń przerwę</button><p class="text-xs text-slate-400">Odliczanie działa również po zablokowaniu i ponownym otwarciu ekranu.</p></div></div>';
document.querySelector('#stepCounter').textContent=isExercise?'Przerwa':'Odpoczynek';document.querySelector('#skipRest').onclick=()=>{flow.restUntil=null;saveFlow();render()};if(restHandle)clearInterval(restHandle);restHandle=setInterval(()=>{const left=Math.max(0,Math.ceil((Number(flow.restUntil)-Date.now())/1000));const clock=document.querySelector('#restClock');if(clock)clock.textContent=fmt(left);if(left<=0){clearInterval(restHandle);restHandle=null;flow.restUntil=null;saveFlow();render()}},250)}
function renderFinishReady(){const root=document.querySelector('#exerciseArea');root.innerHTML='<div class="flex flex-1 flex-col justify-center rounded-3xl bg-emerald-50 p-6 text-center"><div class="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-emerald-100 text-3xl">✓</div><h2 class="mt-4 text-2xl font-black">Wszystkie serie wykonane!</h2><p class="mt-2 text-slate-600">Świetna robota. Zobacz podsumowanie i zakończ trening.</p><button id="showSummary" class="mt-6 w-full rounded-2xl bg-emerald-600 p-4 text-lg font-black text-white">Zakończ trening i pokaż podsumowanie</button></div>';document.querySelector('#stepCounter').textContent='Gotowe';document.querySelector('#finishArea').classList.add('hidden');document.querySelector('#showSummary').onclick=()=>{renderSummary();document.querySelector('#finishArea').classList.remove('hidden');document.querySelector('#finishArea').scrollIntoView({behavior:'smooth',block:'start'})}}
function renderSummary(){const root=document.querySelector('#summary');if(!session)return;root.innerHTML=(session.exercises||[]).map(ex=>{const dur=flow.exerciseDurations?.[ex.id];const sets=setsFor(ex);return '<div class="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div class="min-w-0"><p class="font-bold">'+esc(ex.exercise_name_snapshot)+'</p><p class="text-xs text-slate-500">'+sets.length+' / '+targetSets(ex)+' serii zapisanych</p></div><p class="shrink-0 font-black tabular-nums">'+(dur?fmt(dur):'—')+'</p></div>'}).join('');document.querySelector('#finishIntro').textContent='Łączny czas treningu: '+fmt(session.ended_at?(Number(session.duration_seconds)||elapsed()):elapsed())+'. Czas ćwiczeń obejmuje wykonywanie serii i przerwy między seriami.'}
function notice(msg,error=false){const n=document.querySelector('#notice');n.textContent=msg;n.className='mb-3 text-sm font-semibold '+(error?'text-red-600':'text-emerald-700')}
async function init(){let sid=params.get('session_id');if(!sid){const templateId=params.get('template_id'),scheduledId=params.get('scheduled_id');const recent=await api('workout-sessions?limit=30');const active=recent.find(s=>!s.ended_at&&(scheduledId?String(s.scheduled_workout_id)===String(scheduledId):templateId?String(s.workout_template_id)===String(templateId):false));if(active)sid=active.id;else{let name='Trening';if(templateId){const ts=await api('workout-templates');name=ts.find(t=>String(t.id)===String(templateId))?.name||name}else if(scheduledId){const today=await api('today?date='+new Date().toISOString().slice(0,10));name=today.workout_name||name}const body={workout_name_snapshot:name};if(templateId)body.workout_template_id=Number(templateId);if(scheduledId)body.scheduled_workout_id=Number(scheduledId);const created=await api('workout-sessions',{method:'POST',body:JSON.stringify(body)});sid=created.id}history.replaceState({},'',location.pathname+'?session_id='+sid)}
session=await api('workout-sessions/'+sid);timerFetchedAt=Date.now();loadFlow();if(!flow.exerciseStarts)flow.exerciseStarts={};if(!session.ended_at){timerHandle=setInterval(updateTimer,1000);updateTimer();render()}else{render();updateTimer()} }
document.querySelector('#finish').onclick=async()=>{if(!confirm('Zakończyć trening i zapisać podsumowanie?'))return;const btn=document.querySelector('#finish');btn.disabled=true;btn.textContent='Zapisywanie…';try{await api('workout-sessions/'+session.id,{method:'PUT',body:JSON.stringify({notes:document.querySelector('#sessionNotes').value})});session=await api('workout-sessions/'+session.id);timerFetchedAt=Date.now();if(timerHandle)clearInterval(timerHandle);if(restHandle)clearInterval(restHandle);saveFlow();render();updateTimer();renderSummary();notice('Trening zakończony i zapisany w historii.')}catch(e){notice(e.message,true);btn.disabled=false;btn.textContent='Zakończ trening'}};
init().catch(e=>{document.querySelector('#exerciseArea').innerHTML='<div class="rounded-2xl bg-red-50 p-5 text-red-700">'+esc(e.message)+'</div>';notice('Nie udało się uruchomić treningu.',true)});
</script></body></html>