<!doctype html>
<html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0f172a"><link rel="manifest" href="/trainingapp/public/manifest.json"><script src="https://cdn.tailwindcss.com"></script><link rel="stylesheet" href="/trainingapp/public/css/app.css"><title>FitTrack — Trening</title></head>
<body class="bg-slate-50 text-slate-900"><main class="mx-auto max-w-3xl px-4 pb-10 pt-6 space-y-5"><header><a href="/trainingapp/workouts.php" class="text-sm font-bold text-slate-500">← Plany treningowe</a><h1 id="title" class="mt-2 text-3xl font-black">Trening</h1><p id="subtitle" class="text-slate-500">Zapisuj wynik każdej serii.</p><div class="mt-4 flex items-center justify-between rounded-2xl bg-slate-900 p-4 text-white"><span class="text-sm font-semibold text-slate-300">Czas treningu</span><span id="timer" class="text-2xl font-black tabular-nums">00:00:00</span></div></header><div id="notice" class="text-sm"></div><section id="exerciseArea" class="space-y-4"><p class="rounded-2xl bg-white p-5">Przygotowywanie treningu…</p></section><section id="finishArea" class="hidden rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-3"><label class="block text-sm font-semibold">Notatka z treningu<textarea id="sessionNotes" rows="2" class="mt-1 w-full rounded-xl border p-3"></textarea></label><button id="finish" class="w-full rounded-xl bg-emerald-600 p-4 font-bold text-white">Zakończ trening</button></section></main>
<script>
const API='/trainingapp/api';const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));async function api(p,o={}){const r=await fetch(API+'/'+p,{headers:{'Content-Type':'application/json'},...o});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Błąd API');return d}
const params=new URLSearchParams(location.search);let session=null,timerHandle=null,timerFetchedAt=Date.now();
function elapsed(){if(!session)return 0;return Math.max(0,Number(session.elapsed_seconds)||0)+(session.ended_at?0:Math.floor((Date.now()-timerFetchedAt)/1000))}
function updateTimer(){const s=elapsed();document.querySelector('#timer').textContent=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(n=>String(n).padStart(2,'0')).join(':')}
async function init(){let sid=params.get('session_id');if(!sid){const templateId=params.get('template_id'),scheduledId=params.get('scheduled_id');const recent=await api('workout-sessions?limit=30');const active=recent.find(s=>!s.ended_at&&(scheduledId?String(s.scheduled_workout_id)===String(scheduledId):templateId?String(s.workout_template_id)===String(templateId):false));if(active){sid=active.id}else{let name='Trening';if(templateId){const ts=await api('workout-templates');name=ts.find(t=>String(t.id)===String(templateId))?.name||name}else if(scheduledId){const today=await api('today?date='+new Date().toISOString().slice(0,10));name=today.workout_name||name}const body={workout_name_snapshot:name};if(templateId)body.workout_template_id=Number(templateId);if(scheduledId)body.scheduled_workout_id=Number(scheduledId);const created=await api('workout-sessions',{method:'POST',body:JSON.stringify(body)});sid=created.id}history.replaceState({},'',location.pathname+'?session_id='+sid)}
session=await api('workout-sessions/'+sid);timerFetchedAt=Date.now();render();updateTimer();if(!session.ended_at)timerHandle=setInterval(updateTimer,1000)}
function render(){document.querySelector('#title').textContent=session.workout_name_snapshot||'Trening';document.querySelector('#subtitle').textContent=session.ended_at?'Trening zakończony':'Wyniki zapisują się w historii. Możesz bezpiecznie wrócić do tej strony później.';const root=document.querySelector('#exerciseArea');if(!session.exercises?.length){root.innerHTML='<div class="rounded-3xl bg-white p-5 ring-1 ring-slate-200"><p class="font-bold">Ten trening nie ma przypisanych ćwiczeń.</p><p class="mt-1 text-sm text-slate-500">Wróć do planów i dodaj ćwiczenia do wybranego planu.</p><a class="mt-4 inline-flex rounded-xl bg-slate-900 px-4 py-3 font-bold text-white" href="/trainingapp/workouts.php">Plany treningowe</a></div>';document.querySelector('#finishArea').classList.add('hidden');return}
root.innerHTML=session.exercises.map(ex=>{const timed=ex.exercise_type==='time';const sets=(session.sets||[]).filter(s=>String(s.workout_session_exercise_id)===String(ex.id));const previous=ex.previous_sets||[];const count=Number(ex.sets_target)||3;let rows='';for(let n=1;n<=count;n++){const old=sets.find(s=>Number(s.set_number)===n);const prev=previous.find(s=>Number(s.set_number)===n);rows+='<div class="grid grid-cols-12 items-center gap-2 rounded-xl bg-slate-50 p-2"><span class="col-span-2 text-sm font-bold">Seria '+n+'</span>'+(timed?'':'<label class="col-span-4 text-xs text-slate-500">Ciężar (kg)<input data-weight type="number" min="0" step="0.5" placeholder="'+(prev?prev.weight_kg:'0')+'" value="'+(old?.weight_kg??'')+'" class="mt-1 w-full rounded-lg border p-2 text-base text-slate-900" '+(session.ended_at?'disabled':'')+'></label>')+'<label class="col-span-'+(timed?'7':'3')+' text-xs text-slate-500">'+(timed?'Czas (sek.)':'Powtórzenia')+'<input data-reps type="number" min="0" step="1" placeholder="'+(prev?prev.reps:'')+'" value="'+(old?.reps??'')+'" class="mt-1 w-full rounded-lg border p-2 text-base text-slate-900" '+(session.ended_at?'disabled':'')+'></label><label class="col-span-3 text-xs text-slate-500">RIR<input data-rir type="number" min="0" max="10" step="0.5" value="'+(old?.rir??'')+'" class="mt-1 w-full rounded-lg border p-2 text-base text-slate-900" '+(session.ended_at?'disabled':'')+'></label><button data-save data-ex="'+ex.id+'" data-set="'+n+'" data-timed="'+(timed?'1':'0')+'" class="col-span-12 rounded-lg '+(old?'bg-emerald-100 text-emerald-800':'bg-slate-900 text-white')+' px-3 py-2 text-sm font-bold" '+(session.ended_at?'disabled':'')+'>'+(old?'Zapisano — zapisz ponownie':'Zapisz serię')+'</button></div>'}
const prevText=previous.length?previous.map(s=>'S'+s.set_number+': '+(timed?s.reps+' s':s.weight_kg+' kg × '+s.reps)).join(' · '):'Brak wcześniejszego wyniku tego ćwiczenia';
const target=timed?(ex.min_reps_target?ex.min_reps_target+' s':'czas według planu'):(ex.min_reps_target?ex.min_reps_target+(ex.max_reps_target&&ex.max_reps_target!==ex.min_reps_target?'-'+ex.max_reps_target:'')+' powt.':'powtórzenia według planu');
return '<article class="rounded-3xl bg-white p-5 shadow-sm ring-1 ring-slate-200 space-y-3"><div><h2 class="text-xl font-black">'+esc(ex.exercise_name_snapshot)+'</h2><p class="text-sm text-slate-500">'+esc(ex.muscle_group||'')+' · '+(ex.sets_target||3)+' serii · cel: '+target+'</p></div><div class="rounded-xl bg-blue-50 p-3"><p class="text-xs font-bold text-blue-800">POPRZEDNI TRENING</p><p class="mt-1 text-sm text-blue-900">'+esc(prevText)+'</p></div><div class="space-y-2">'+rows+'</div></article>'}).join('');
root.querySelectorAll('[data-save]').forEach(b=>b.onclick=async()=>{const row=b.closest('.grid');const reps=row.querySelector('[data-reps]').value;if(reps===''){notice(b.dataset.timed==='1'?'Wpisz czas w sekundach.':'Wpisz liczbę powtórzeń.');return}b.disabled=true;try{await api('workout-sessions/'+session.id+'/sets',{method:'POST',body:JSON.stringify({workout_session_exercise_id:Number(b.dataset.ex),set_number:Number(b.dataset.set),weight_kg:row.querySelector('[data-weight]')?.value||0,reps:Number(reps),rir:row.querySelector('[data-rir]').value})});notice('Wynik serii zapisany.');session=await api('workout-sessions/'+session.id);timerFetchedAt=Date.now();render()}catch(e){notice(e.message,true)}finally{b.disabled=false}});
document.querySelector('#finishArea').classList.toggle('hidden',Boolean(session.ended_at));if(session.ended_at){document.querySelector('#finishArea').classList.add('hidden');root.insertAdjacentHTML('afterbegin','<div class="rounded-2xl bg-emerald-50 p-4 font-semibold text-emerald-800">Trening zakończony i zapisany w historii.</div>')}else document.querySelector('#finishArea').classList.remove('hidden')}
function notice(msg,error=false){const n=document.querySelector('#notice');n.textContent=msg;n.className='text-sm '+(error?'text-red-600':'text-emerald-700')}
document.querySelector('#finish').onclick=async()=>{if(!confirm('Zakończyć trening?'))return;try{await api('workout-sessions/'+session.id,{method:'PUT',body:JSON.stringify({notes:document.querySelector('#sessionNotes').value})});session=await api('workout-sessions/'+session.id);timerFetchedAt=Date.now();if(timerHandle)clearInterval(timerHandle);render();updateTimer();notice('Trening zakończony.')}catch(e){notice(e.message,true)}};
init().catch(e=>{document.querySelector('#exerciseArea').innerHTML='<div class="rounded-2xl bg-red-50 p-5 text-red-700">'+esc(e.message)+'</div>';notice('Nie udało się uruchomić treningu.',true)});
</script></body></html>